export const AdmissionStatus = {
  SEM_ADMISSAO: 'SEM_ADMISSAO',
  PREINSCRITO_MESTRADO_POS_GRADUACAO: 'PREINSCRITO_MESTRADO_POS_GRADUACAO',
  AGUARDANDO_DIA_DA_PROVA: 'AGUARDANDO_DIA_DA_PROVA',
  NAO_ADMITIDO: 'NAO_ADMITIDO',
  ADMITIDO_SEM_MATRICULA: 'ADMITIDO_SEM_MATRICULA',
  ALUNO_MATRICULADO: 'ALUNO_MATRICULADO',
  AGUARDANDO_RESULTADO: 'AGUARDANDO_RESULTADO',
  DIA_DA_PROVA: 'DIA_DA_PROVA'
}
