export const DocumentTypeEnum = {
  BILHETE_IDENTIDADE: 1,
  CERTIFICADO_COM_NOTAS: 7,
  CERTIFICADO:1,
  PROJECTO_DE_INVESTIGACAO_CIENTIFICA: 17,
  CURRICULUM_VITAE: 13,
  DECLARACAO_DE_PROVICIENCIA_EM_INGLES: 18,
}
