export enum TipoCalendario {
  AFECTACAO = 'AFECTACAO',
  CRIACAO_HORARIO = 'CRIACAO_HORARIO',
  INSCRICAO_ESTUDANTES_NOVO = 'INSCRICAO_ESTUDANTES_NOVO',
  CONFIRMACAO_MATRICULA = 'CONFIRMACAO_MATRICULA',
  EXAME_ACESSO = 'EXAME_ACESSO',
  ABERTURA_ANO_LECTIVO = 'ABERTURA_ANO_LECTIVO',
  CANDIDATURA_DOCENTES = 'CANDIDATURA_DOCENTES',
  SELECCAO_HORARIOS = 'SELECCAO_HORARIOS',
  RECURSO = 'RECURSO',
  EXAME_ESPECIAL = 'EXAME_ESPECIAL',
  MELHORIA_NOTAS = 'MELHORIA_NOTAS',
  REINGRESSO = 'REINGRESSO',
  SUBSTITUICAO_UC = 'SUBSTITUICAO_UC',
  MUDANCA_CURSO_INTERNA = 'MUDANCA_CURSO_INTERNA',
  CADEIRAS_EXTRACURRICULARES = 'CADEIRAS_EXTRACURRICULARES',
  MATRICULAS = 'MATRICULAS',
}

export const TIPO_CALENDARIO_CODIGO = {
  [TipoCalendario.AFECTACAO]: 1,
  [TipoCalendario.CRIACAO_HORARIO]: 2,
  [TipoCalendario.INSCRICAO_ESTUDANTES_NOVO]: 3,
  [TipoCalendario.CONFIRMACAO_MATRICULA]: 4,
  [TipoCalendario.EXAME_ACESSO]: 5,
  [TipoCalendario.ABERTURA_ANO_LECTIVO]: 6,
  [TipoCalendario.CANDIDATURA_DOCENTES]: 7,
  [TipoCalendario.SELECCAO_HORARIOS]: 8,
  [TipoCalendario.RECURSO]: 9,
  [TipoCalendario.EXAME_ESPECIAL]: 10,
  [TipoCalendario.MELHORIA_NOTAS]: 11,
  [TipoCalendario.REINGRESSO]: 12,
  [TipoCalendario.SUBSTITUICAO_UC]: 13,
  [TipoCalendario.MUDANCA_CURSO_INTERNA]: 14,
  [TipoCalendario.CADEIRAS_EXTRACURRICULARES]: 15,
  [TipoCalendario.MATRICULAS]: 16,
} as const

export const CODIGO_TIPO_CALENDARIO = {
  1: TipoCalendario.AFECTACAO,
  2: TipoCalendario.CRIACAO_HORARIO,
  3: TipoCalendario.INSCRICAO_ESTUDANTES_NOVO,
  4: TipoCalendario.CONFIRMACAO_MATRICULA,
  5: TipoCalendario.EXAME_ACESSO,
  6: TipoCalendario.ABERTURA_ANO_LECTIVO,
  7: TipoCalendario.CANDIDATURA_DOCENTES,
  8: TipoCalendario.SELECCAO_HORARIOS,
  9: TipoCalendario.RECURSO,
  10: TipoCalendario.EXAME_ESPECIAL,
  11: TipoCalendario.MELHORIA_NOTAS,
  12: TipoCalendario.REINGRESSO,
  13: TipoCalendario.SUBSTITUICAO_UC,
  14: TipoCalendario.MUDANCA_CURSO_INTERNA,
  15: TipoCalendario.CADEIRAS_EXTRACURRICULARES,
  16: TipoCalendario.MATRICULAS,
} as const

export type CodigoTipoCalendario =
  (typeof TIPO_CALENDARIO_CODIGO)[TipoCalendario]
