const matricula = [
  {
    disciplina: 'Iniciação a Cardiopneumologia',
    semestre: 'I SEMESTRE',
    classe: '1º ano',
    duracaoDisciplina: 'Semestral',
    codigoDisciplina: '743',
    codigoGrade: '173',
    valorInscricao: '1600',
  },
  {
    disciplina: 'Biologia',
    semestre: 'I SEMESTRE',
    classe: '1º ano',
    duracaoDisciplina: 'Semestral',
    codigoDisciplina: '809',
    codigoGrade: '171',
    valorInscricao: '1600',
  },
  {
    disciplina: 'Metodologias de Investigação Científica',
    semestre: 'I SEMESTRE',
    classe: '1º ano',
    duracaoDisciplina: 'Semestral',
    codigoDisciplina: '1031',
    codigoGrade: '2390',
    valorInscricao: '1600',
  },
  {
    disciplina: 'Matemática',
    semestre: 'I SEMESTRE',
    classe: '1º ano',
    duracaoDisciplina: 'Anual',
    codigoDisciplina: '475',
    codigoGrade: '2492',
    valorInscricao: '1600',
  },
  {
    disciplina: 'Bioquímica',
    semestre: 'I SEMESTRE',
    classe: '1º ano',
    duracaoDisciplina: 'Semestral',
    codigoDisciplina: '67',
    codigoGrade: '2712',
    valorInscricao: '1600',
  },
  {
    disciplina: 'Metodologias de Investigação Científica',
    semestre: 'I SEMESTRE',
    classe: '1º ano',
    duracaoDisciplina: 'Semestral',
    codigoDisciplina: '1031',
    codigoGrade: '2454',
    valorInscricao: '1600',
  },
  {
    disciplina: 'Bioquímica',
    semestre: 'I SEMESTRE',
    classe: '1º ano',
    duracaoDisciplina: 'Semestral',
    codigoDisciplina: '916',
    codigoGrade: '172',
    valorInscricao: '1600',
  },
  {
    disciplina: 'Estatística',
    semestre: 'II SEMESTRE',
    classe: '1º ano',
    duracaoDisciplina: 'Semestral',
    codigoDisciplina: '32',
    codigoGrade: '180',
    valorInscricao: '1600',
  },
  {
    disciplina: 'Biofísica',
    semestre: 'I SEMESTRE',
    classe: '1º ano',
    duracaoDisciplina: 'Semestral',
    codigoDisciplina: '71',
    codigoGrade: '2778',
    valorInscricao: '1600',
  },
  {
    disciplina: 'Metodismo e Doutrina Social',
    semestre: 'I SEMESTRE',
    classe: '1º ano',
    duracaoDisciplina: 'Semestral',
    codigoDisciplina: '520',
    codigoGrade: '1928',
    valorInscricao: '1600',
  },
  {
    disciplina: 'Matemática',
    semestre: 'I SEMESTRE',
    classe: '1º ano',
    duracaoDisciplina: 'Semestral',
    codigoDisciplina: '1268',
    codigoGrade: '2434',
    valorInscricao: '1600',
  },
  {
    disciplina: 'Biofísica',
    semestre: 'II SEMESTRE',
    classe: '1º ano',
    duracaoDisciplina: 'Semestral',
    codigoDisciplina: '71',
    codigoGrade: '178',
    valorInscricao: '1600',
  },
  {
    disciplina: 'Anatomia',
    semestre: 'II SEMESTRE',
    classe: '1º ano',
    duracaoDisciplina: 'Semestral',
    codigoDisciplina: '600',
    codigoGrade: '177',
    valorInscricao: '1600',
  },
  {
    disciplina: 'Biologia',
    semestre: 'I SEMESTRE',
    classe: '1º ano',
    duracaoDisciplina: 'Semestral',
    codigoDisciplina: '809',
    codigoGrade: '1960',
    valorInscricao: '1600',
  },
  {
    disciplina: 'Biologia',
    semestre: 'I SEMESTRE',
    classe: '1º ano',
    duracaoDisciplina: 'Semestral',
    codigoDisciplina: '1262',
    codigoGrade: '1957',
    valorInscricao: '1600',
  },
  {
    disciplina: 'Estatística',
    semestre: 'II SEMESTRE',
    classe: '1º ano',
    duracaoDisciplina: 'Semestral',
    codigoDisciplina: '32',
    codigoGrade: '2344',
    valorInscricao: '1600',
  },
  {
    disciplina: 'Matemática',
    semestre: 'I SEMESTRE',
    classe: '1º ano',
    duracaoDisciplina: 'Semestral',
    codigoDisciplina: '26',
    codigoGrade: '174',
    valorInscricao: '1600',
  },
  {
    disciplina: 'Anatomofisiologia',
    semestre: 'I SEMESTRE',
    classe: '1º ano',
    duracaoDisciplina: 'Semestral',
    codigoDisciplina: '740',
    codigoGrade: '170',
    valorInscricao: '1600',
  },
  {
    disciplina: 'Fisiologia I',
    semestre: 'II SEMESTRE',
    classe: '1º ano',
    duracaoDisciplina: 'Semestral',
    codigoDisciplina: '741',
    codigoGrade: '181',
    valorInscricao: '1600',
  },
  {
    disciplina: 'Protecção e Segurança',
    semestre: 'II SEMESTRE',
    classe: '1º ano',
    duracaoDisciplina: 'Semestral',
    codigoDisciplina: '745',
    codigoGrade: '183',
    valorInscricao: '1600',
  },
  {
    disciplina: 'Biofísica',
    semestre: 'II SEMESTRE',
    classe: '1º ano',
    duracaoDisciplina: 'Semestral',
    codigoDisciplina: '71',
    codigoGrade: '2362',
    valorInscricao: '1600',
  },
  {
    disciplina: 'Patologia Geral',
    semestre: 'II SEMESTRE',
    classe: '1º ano',
    duracaoDisciplina: 'Semestral',
    codigoDisciplina: '744',
    codigoGrade: '182',
    valorInscricao: '1600',
  },
  {
    disciplina: 'Psicologia I',
    semestre: 'I SEMESTRE',
    classe: '1º ano',
    duracaoDisciplina: 'Semestral',
    codigoDisciplina: '742',
    codigoGrade: '176',
    valorInscricao: '1600',
  },
  {
    disciplina: 'Metodismo e Doutrina Social',
    semestre: 'I SEMESTRE',
    classe: '1º ano',
    duracaoDisciplina: 'Semestral',
    codigoDisciplina: '520',
    codigoGrade: '175',
    valorInscricao: '1600',
  },
]

const perfil = {
  codresposta: 200,
  msgresposta: 'Dados encontrados com sucesso',
  codigo_preinscricao: '19',
  nome_completo: 'Elisa Lukeni da Silva Cristóvão',
  sexo: 'Feminino',
  data_nascimento: '1979-12-07',
  email: 'None',
  bilhete_identidade: '000314806LA039',
  contactos: 'None',
  codigo_admissao: '19',
  data_admissao: '2008-01-01T00:00:00',
  codigo_matricula: '328',
  data_matricula: '2008-01-01',
  estado_matricula: 'diplomado',
  codigo_curso: '9',
  codigo_aluno: '19',
  curso: 'Direito',
  polo: 'Luanda - Kinaxixi',
}
